Updated women_laws.html file.
swapnilsparsh/Rescue pull request #129
Opened 2021-03-10 10:29 UTC by AishwaryaKaranth

## Related Issuse or bug
  - Improve Women_laws.html documentation.

Fixes: #117

I have formatted the existing documentation (women_laws.html) and added some CSS effects to each paragraph.

2021-03-11 14:34 UTC, swapnilsparsh reviewed
**Fix the errors**
![e](https://user-images.githubusercontent.com/69387608/110802963-b5b94f00-82a4-11eb-9a50-22717220e8e2.png)
![ec](https://user-images.githubusercontent.com/69387608/110802969-b7831280-82a4-11eb-89ad-5352ea59cbd8.png)

**Dont use italics, just highlight it with blue colour as you have done and in some laws there is no highlighted text so do some research and if you want to change the details then change it and highlight the required text.**
![italics](https://user-images.githubusercontent.com/69387608/110802967-b6ea7c00-82a4-11eb-9b8a-9a6d0b95c6f3.png)

2021-03-11 14:47 UTC, AishwaryaKaranth commented
I'm not sure what is causing the error, I only edited women_laws.html file. As for the laws, I'll make the necessary changes.

2021-03-12 08:24 UTC, sakshikhachane commented
> **Fix the errors**
> ![e](https://user-images.githubusercontent.com/69387608/110802963-b5b94f00-82a4-11eb-9a50-22717220e8e2.png)
> ![ec](https://user-images.githubusercontent.com/69387608/110802969-b7831280-82a4-11eb-89ad-5352ea59cbd8.png)

@swapnilsparsh I have checked this and found that the error was there before only.

> **Dont use italics, just highlight it with blue colour as you have done and in some laws there is no highlighted text so do some research and if you want to change the details then change it and highlight the required text.**
> ![italics](https://user-images.githubusercontent.com/69387608/110802967-b6ea7c00-82a4-11eb-9b8a-9a6d0b95c6f3.png)

@AishwaryaKaranth Do the above changes.

2021-03-12 08:34 UTC, sakshikhachane requested changes

2021-03-12 08:34 UTC, sakshikhachane commented on main_app/templates/main_app/women_laws.html
> +            padding-left: 0.5rem;
Please add padding-right as well for this which is equal to padding-left. Also, increase the padding-left as well.

2021-03-12 08:34 UTC, sakshikhachane commented on main_app/templates/main_app/women_laws.html
> +                    <p class="description"><span style="background:#a8dadc">Sati (Prevention) Act</span>, 1987 is a law enacted by Government of Rajasthan in 1987.
@AishwaryaKaranth Please edit the content in bullet form for every law. Right now, it is less bit unreadable.

2021-03-12 18:02 UTC, swapnilsparsh commented
> > **Fix the errors**
> > ![e](https://user-images.githubusercontent.com/69387608/110802963-b5b94f00-82a4-11eb-9a50-22717220e8e2.png)
> > ![ec](https://user-images.githubusercontent.com/69387608/110802969-b7831280-82a4-11eb-89ad-5352ea59cbd8.png)
> 
> @swapnilsparsh I have checked this and found that the error was there before only.
> 
> > **Dont use italics, just highlight it with blue colour as you have done and in some laws there is no highlighted text so do some research and if you want to change the details then change it and highlight the required text.**
> > ![italics](https://user-images.githubusercontent.com/69387608/110802967-b6ea7c00-82a4-11eb-9b8a-9a6d0b95c6f3.png)
> 
> @AishwaryaKaranth Do the above changes.

Run `python manage.py migrate` then this error will resolve.

2021-03-16 08:54 UTC, sakshikhachane commented
@AishwaryaKaranth Any updates on this PR?

2021-03-16 08:56 UTC, AishwaryaKaranth commented
> @AishwaryaKaranth Any updates on this PR?

Sorry for the delay, will submit a PR by tonight.

2021-03-19 10:26 UTC, closed without merging