Fixed HTML documentation
swapnilsparsh/Rescue pull request #130
Opened 2021-03-10 14:07 UTC by medhavi11

## Related Issuse or bug
  - Info about Issue or bug

Fixes: #[issue number that will be closed through this PR]

#### Describe the changes you've made
A clear and concise description of what you have done to successfully close your assigned issue. Any new files? or anything you feel to let us know!

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. 

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
A clear and concise description of it.

## Checklist:

- [ ] My code follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots

 Original           | Updated
 :--------------------: |:--------------------:
 **original screenshot**  | <b>updated screenshot </b> |

2021-03-10 14:09 UTC, medhavi11 commented
#117 fixed

2021-03-11 14:44 UTC, swapnilsparsh reviewed
You have done great job, you have to make few changes:
1.  Use bullets where there are long paragraphs to make it easy to read.
2.  Highlight the main text by some different colour in the paragraphs.

2021-03-11 14:49 UTC, medhavi11 commented
Sure!!!

2021-03-12 08:36 UTC, sakshikhachane commented
> #117 fixed

Hey @medhavi11,
Please write the issue number in `Fixes: #[issue number that will be closed through this PR]` This section.

2021-03-12 08:41 UTC, sakshikhachane requested changes

2021-03-12 08:41 UTC, sakshikhachane commented on .vscode/settings.json
> +    "liveServer.settings.port": 501
@medhavi11 Please remove this file from this PR.

2021-03-12 08:41 UTC, sakshikhachane commented on main_app/templates/main_app/women_laws.html
> +                    <p>The Divorce Act 1869 provides for the grounds for dissolution of marriage. Both the husband and wife can move to court to seek a decree for divorce under this act.
Please add bullets for the content that is big enough to read. So that it will be in an organized manner.

2021-03-14 03:20 UTC, sakshikhachane commented
@medhavi11 Please give an update on the progress.

2021-03-14 09:33 UTC, medhavi11 commented
> @medhavi11 Please give an update on the progress.

Still working on it!

2021-03-19 10:26 UTC, closed without merging