Added top button in women_rights.html and women_laws.html
swapnilsparsh/Rescue pull request #135
Opened 2021-03-11 16:15 UTC by kanishka8276

## Related Issuse or bug
  #123 

Fixes: #[issue number that will be closed through this PR]

#### Describe the changes you've made
I have added a top button in n women_rights.html and women_laws.html. It is displayed in the bottom right corner and will take you to the top of the page when clicked. I have added required CSS and JavaScript.

## Type of change

Please delete options that are not relevant.

- [ x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x ] My code follows the style guidelines of this project.
- [ x] I have performed a self-review of my own code.
- [ x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ x] New and existing unit tests pass locally with my changes.
- [ x] Any dependent changes have been merged and published in downstream modules.

## Screenshots
 Top button 
 
![Screenshot (56)](https://user-images.githubusercontent.com/66053534/110818039-e902da80-82b2-11eb-9880-012b753bc5c7.png)
Top button when pointer is over it
![Screenshot (57)](https://user-images.githubusercontent.com/66053534/110818098-f750f680-82b2-11eb-803b-b863532d5399.png)

2021-03-11 16:41 UTC, swapnilsparsh commented
Add this type of top button
![top](https://user-images.githubusercontent.com/69387608/110821926-90cdd780-82b6-11eb-894f-0b4b322bd7fe.png)

1. There is no smooth transition so fix it.
2. Add top button to every page.

2021-03-11 16:43 UTC, kanishka8276 commented
Ok! I will do that

2021-03-11 19:22 UTC, kanishka8276 commented
I have changed the top button as suggested by you in women_rights.html and women_laws.html.
Please review it. If it's ok now then I Will add the button for all the other pages. 
Also sorry for putting top.png in template folder but I don't know why but when I ran it, it wasn't able to load the image from the images folder in static folder.

2021-03-12 05:51 UTC, kanishka8276 commented
I have made the transition smooth. Please review.

2021-03-12 09:00 UTC, sakshikhachane commented
Hey @kanishka8276,
<img width="67" alt="f" src="https://user-images.githubusercontent.com/53635792/110916462-d46c2400-833e-11eb-9439-cd526cd1916d.PNG">
The button is having `Top` written on it. Refer to the picture sent by @swapnilsparsh and try doing a button similar to it.
By smooth transition, we mean that after clicking on the button, the page should move up slowly not directly to the top.

2021-03-12 09:13 UTC, kanishka8276 commented
Ok,I will do that.

2021-03-12 09:37 UTC, kanishka8276 commented
@sakshikhachane I have made the required changes.  And by smooth transition I meant that only.
I have used the css scroll-behavior :smooth to make the scrolling to the top smooth.

2021-03-12 12:49 UTC, sakshikhachane commented
> @sakshikhachane I have made the required changes. And by smooth transition I meant that only.
> I have used the css scroll-behavior :smooth to make the scrolling to the top smooth.

It is looking quite good. Just a few changes-
- [ ] Make the white arrow slightly smaller.
- [ ] Make the black circle bigger in size.
- [ ] Add the hover effect ( on hovering make the white arrow black and black circle white).

2021-03-12 12:51 UTC, kanishka8276 commented
Ok!

2021-03-12 13:44 UTC, kanishka8276 commented
@sakshikhachane I did the suggested changes. Please review.

2021-03-12 15:16 UTC, sakshikhachane requested changes
As the changes suggested by me were not done completely, I have reviewed it again. Please do the changes.

2021-03-12 15:16 UTC, sakshikhachane commented on main_app/templates/main_app/helpline_numbers.html
> +<!-----------------------------------------------------------Top Button---------------------------------------------------------------------------->
Remove this comment. Because of this `scroll-behavior` is getting hampered. You can check this.

2021-03-12 15:16 UTC, sakshikhachane commented on main_app/templates/main_app/helpline_numbers.html
> +   #myBtn {
Add ` background-color: black;` in this.

2021-03-12 15:16 UTC, sakshikhachane commented on main_app/templates/main_app/helpline_numbers.html
> +      background-color: white;
Add ` border: 2px black solid;` in this.

2021-03-12 15:20 UTC, kanishka8276 commented
Ok!

2021-03-12 15:32 UTC, kanishka8276 commented
@sakshikhachane I  Did the requested changes.

2021-03-12 16:08 UTC, sakshikhachane commented
@kanishka8276 Just one last change apply this button on every page starting from the home page. Then it ready to be merged.

2021-03-12 16:11 UTC, kanishka8276 commented
Ok

2021-03-12 16:52 UTC, kanishka8276 commented
@sakshikhachane  I have added the top button to all the pages. I hope it's now ready to merge!!

2021-03-12 16:58 UTC, kanishka8276 commented
@sakshikhachane I have added the top button to all the pages. I hope it's now ready to merge!!

2021-03-12 17:08 UTC, sakshikhachane commented
> @sakshikhachane I have added the top button to all the pages. I hope it's now ready to merge!!

Can you please have a look at `emergency` and `emergency_contact` page? 
It seems that they are not working properly. Also `emergency` page after adding one contact.

2021-03-12 17:11 UTC, kanishka8276 commented
Ok!

2021-03-12 17:18 UTC, kanishka8276 commented
@sakshikhachane I hope it's working fine now.

2021-03-12 21:14 UTC, swapnilsparsh requested changes
**After logging in when trying to add contact then this error is giving and on clickinng the emergency also its showing the same error**

![c](https://user-images.githubusercontent.com/69387608/110999142-eb922c80-83a5-11eb-888b-070f8d095d78.png)

2021-03-13 03:37 UTC, kanishka8276 commented
Shall I remove the top button from these 2 pages because I tried to fix it but it is not working for these 2 pages.

2021-03-13 06:05 UTC, kanishka8276 commented
@swapnilsparsh @sakshikhachane  Made the required changes and tested it. Now it's working fine.

2021-03-13 07:16 UTC, sakshikhachane approved these changes

2021-03-13 17:18 UTC, merged