Login page's UI made similar to register page's UI
swapnilsparsh/Rescue pull request #167
Opened 2021-03-17 17:00 UTC by manasivaraiya

## Related Issue or bug
  - Info about Issue or bug

Fixes: #[issue number that will be closed through this PR]

#### Describe the changes you've made
A clear and concise description of what you have done to successfully close your assigned issue. Any new files? or anything you feel to let us know!

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. 

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
A clear and concise description of it.

## Checklist:

- [ ] My code follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots

 Original           | Updated
 :--------------------: |:--------------------:
 **original screenshot**  | <b>updated screenshot </b> |

2021-03-18 10:53 UTC, sakshikhachane requested changes
@manasivaraiya Please do the requested changes.

2021-03-18 10:53 UTC, sakshikhachane commented on main_app/templates/main_app/login.html
>                          Registered
- [ ] Change `WELCOME` to `WELCOME TO RESCUE` and apply CSS to it similar to `register` page.
- [ ] Change the image of `login` page to the image present on the `register` page.

2021-03-18 10:53 UTC, sakshikhachane commented on main_app/templates/main_app/login.html
> +                    <div class="login">
Please fix the space above `WELCOME` for the devices with smaller widths and heights.
![image](https://user-images.githubusercontent.com/53635792/111614775-ffa2b780-8805-11eb-8d1c-81e426cc84e4.png)

2021-03-19 10:40 UTC, sakshikhachane commented
@manasivaraiya Any updates?

2021-03-20 17:46 UTC, manasivaraiya commented
In my repo I do not find any such space above welcome on login page! Could you please check once again and let me know?
I have committed the 2 changes proposed above .

2021-03-20 17:46 UTC, manasivaraiya commented
> @manasivaraiya Any updates?

really sorry for the late reply.

2021-03-21 13:04 UTC, sakshikhachane approved these changes

2021-03-23 03:53 UTC, sakshikhachane commented
@manasivaraiya Please resolve the conflicts.

2021-03-28 17:02 UTC, mansijain980 commented
@sakshikhachane can i proceed further?

2021-03-29 20:24 UTC, swapnilsparsh commented
@manasivaraiya Any updates ?

2021-04-04 17:55 UTC, closed without merging