Updated Webpage of Women helpline numbers in Site under the file helpline_numbers.
swapnilsparsh/Rescue pull request #169
Opened 2021-03-17 18:47 UTC by mansijain980

##Updated with new Features

Fixes:  #124
#### Description 

I have added a lot of features on webpage of women helpline by bootstrap , css , html , javascipt  likeuser can go above the page directly by clicking button .
Statewise helpline numbers are also linked . 
An attractive page. 
Now , it is easy for user to search for a particular sate helpline numbers .

## Type of change
- [ ] New feature (non-breaking change which adds functionality)
- 

## Checklist:
-  My code follows the code style of this project.
-  My code follows the style guidelines of this project.
-  I have performed a self-review of my own code.

## Screenshots

 
![image](https://user-images.githubusercontent.com/63226239/111521476-32ee3380-877f-11eb-853b-5bd270daf118.png)

2021-03-17 18:51 UTC, mansijain980 commented
Hey ! @sakshikhachane  I have Requested a PR for this issue . Please let me know if there is any problem with something that i have done .
Please marge a pull request . 
Thanks

2021-03-17 20:27 UTC, swapnilsparsh commented
@sakshikhachane Have a look.

2021-03-18 11:09 UTC, sakshikhachane requested changes
@mansijain980
- [ ]  Please keep the format/ design of the `helpline_numbers` page the same as previous.
- [ ] Just add the rest of the numbers below it. 
- [ ] Also, keep your branch even with the `master` branch of this repo.

2021-03-18 11:09 UTC, sakshikhachane commented on main_app/static/css/styles.css
> +@import url("https://fonts.googleapis.com/css?family=Sunflower:300");
For now please use inline CSS only. 
Don't add CSS in `styles.css` file.

2021-03-18 11:09 UTC, sakshikhachane commented on main_app/templates/main_app/login.html
> +<!DOCTYPE html> {% extends "main_app/common.html" %} {% load static %}
Please remove the `login.html` file from the PR.

2021-03-18 11:09 UTC, sakshikhachane commented on main_app/templates/main_app/register.html
> +<html lang="en">
Remove `register.html` file from PR.

2021-03-19 10:41 UTC, sakshikhachane commented
@mansijain980 Any updates?

2021-03-19 12:01 UTC, mansijain980 commented
> @mansijain980 Any updates?

Yes maam ... i m working on it . Actually i started working on some other issue. By tomorrow evening , I will commit changes and append rows on that table .
Thanks.

2021-03-20 15:19 UTC, mansijain980 commented
@sakshikhachane ma'am can u tell me the color of background? It should be white na?

2021-03-21 13:05 UTC, sakshikhachane commented
> @sakshikhachane ma'am can u tell me the color of background? It should be white na?

Keep the background the same as it was before doing the changes.

2021-03-22 08:27 UTC, mansijain980 commented
@sakshikhachane Can u check it now please?

2021-03-22 10:33 UTC, sakshikhachane requested changes
@mansijain980 

- [ ] You have to remove the files from PR, not from your forked repo. Please revert the changes or make a new PR.

- [ ] Please fix this - 
![image](https://user-images.githubusercontent.com/53635792/111976599-cfba2380-8b27-11eb-8616-b204110a8fd2.png)

- [ ] Remove this as well. 
![image](https://user-images.githubusercontent.com/53635792/111976757-fe37fe80-8b27-11eb-8413-b98f5038b411.png)

2021-03-23 06:22 UTC, closed without merging