Fixed the extra white space for the issue #103
swapnilsparsh/Rescue pull request #181
Opened 2021-03-19 18:49 UTC by simranbhalla3

## Related Issue or bug
  - The issue was related on fixing the extra white space  which is there below the carousel at homepage 

Fixes: #[103]

#### Describe the changes you've made
I have fixed the extra space by making proper allignment using padding and margin changes in css

## Type of change

Please delete options that are not relevant.

- [ Y] Bug fix (non-breaking change which fixes an issue)
- [ N] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. 

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

## Checklist:

- [Y ] My code follows the style guidelines of this project.
- [ Y] I have performed a self-review of my own code.
- [ Y] I have commented my code, particularly in hard-to-understand areas.
- [ Y] I have made corresponding changes to the documentation.
- [ Y] My changes generate no new warnings.
- [ Y] I have added tests that prove my fix is effective or that my feature works.
- [ Y] New and existing unit tests pass locally with my changes.
- [ Y] Any dependent changes have been merged and published in downstream modules.

## Screenshots

 Original           | Updated
 :--------------------: |:--------------------:
 **original screenshot**  | <b>updated screenshot </b> 
![image](https://user-images.githubusercontent.com/73423545/111828800-d66f4d80-8911-11eb-815c-cca5ab6052a3.png)

2021-03-20 07:20 UTC, sakshikhachane requested changes
Please fix the `home` page for small screens. 
![image](https://user-images.githubusercontent.com/53635792/111862352-d3f50e00-897a-11eb-95af-3bde73a314f3.png)

2021-03-20 09:16 UTC, simranbhalla3 commented
> Please fix the `home` page for small screens.
> ![image](https://user-images.githubusercontent.com/53635792/111862352-d3f50e00-897a-11eb-95af-3bde73a314f3.png)

![rescue1](https://user-images.githubusercontent.com/73423545/111865081-e8d99d80-898a-11eb-963a-08d39905c8fc.gif)
 
 I have made the necessary changes and the extra white space had been removed. Kindly check

2021-03-20 13:05 UTC, sakshikhachane commented
@simranbhalla3 Please check for the `Galaxy Fold` screen.

2021-03-22 10:37 UTC, sakshikhachane commented
@simranbhalla3 Any updates?

2021-03-23 05:53 UTC, simranbhalla3 commented
> @simranbhalla3 Any updates?

Made the changes required please check

2021-03-23 06:17 UTC, sakshikhachane requested changes
The footer is currently floated. It is not at the bottom of the website. I have attached the image for your reference. Please fix this.
![image](https://user-images.githubusercontent.com/53635792/112101882-6a207280-8bcd-11eb-8e9c-9f4c8f310f57.png)

2021-04-07 12:06 UTC, sakshikhachane commented
@simranbhalla3 Any updates?

2021-04-07 12:22 UTC, simranbhalla3 commented
> @simranbhalla3 Any updates?

i guess i got unassigned

2021-04-07 12:27 UTC, sakshikhachane commented
Okay! Closing this PR.

2021-04-07 12:27 UTC, closed without merging