added check for username and email
swapnilsparsh/Rescue pull request #240
Opened 2021-04-09 10:24 UTC by niksm7

## Related Issue or bug
The register form expects username and email which should be unique according to Django authentication but when some other user tries to register with already existing username or email they only come to know about the problem after submitting the form which is not good user experience.

Fixes: #226 

#### Describe the changes you've made

I have added Ajax functionality to dynamically check the uniqueness of the username and email while registering. The Ajax call checks if the user with entered name or email exists and if it is so then the user is alerted with a message. Even after showing the error if the user tries to register then they are shown a window alert  stating the problem. Also if the user doesn't match the password and confirm password field then they are alerted about the same. This functionality of uniqueness is also maintained with the google login as well.

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

I have tested it against various scenarios and it works perfectly fine also shown in the video below

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] New and existing unit tests pass locally with my changes.
- [x] Any dependent changes have been merged and published in downstream modules.

## Screenshots

https://user-images.githubusercontent.com/55614782/114166703-b8629f00-994b-11eb-8bd1-5e61b3c11543.mov

2021-04-10 15:33 UTC, swapnilsparsh commented
@niksm7 Great work !!
Just add a feature that if username/email is available then it should say username/email is available with a green tick  and if it's not available then it should say not available with a cross symbol.

2021-04-10 15:35 UTC, swapnilsparsh requested changes
Just add a feature that if username/email is available then it should say username/email is available with a green tick and if it's not available then it should say not available with a cross symbol.

2021-04-11 09:37 UTC, niksm7 commented
Have added the requested feature @swapnilsparsh 
<img width="1434" alt="Screenshot 2021-04-11 at 3 04 42 PM" src="https://user-images.githubusercontent.com/55614782/114299178-939b3280-9ad7-11eb-92cd-578b88cc1338.png">

2021-04-11 17:16 UTC, swapnilsparsh commented on main_app/templates/main_app/register.html
> +                                x.innerHTML = "<br>username not available <br>"
Make the first letter capital

2021-04-11 17:17 UTC, swapnilsparsh commented on main_app/templates/main_app/register.html
> +                                x.innerHTML = "<br>username not available <br>"
Make the first letter capital

2021-04-11 17:17 UTC, swapnilsparsh commented on main_app/templates/main_app/register.html
> +                                x.innerHTML = "<br>username is available <br>"
Make the first letter capital

2021-04-11 17:18 UTC, swapnilsparsh requested changes
Resolve the conflicts

2021-04-11 17:34 UTC, niksm7 commented
Changes have been done and conflicts resolved @swapnilsparsh

2021-04-12 12:28 UTC, sakshikhachane commented
Hey @niksm7,
Still, there are conflicts. Please resolve them.

2021-04-12 12:34 UTC, niksm7 commented
Done @sakshikhachane

2021-04-14 17:00 UTC, merged