improved footer
swapnilsparsh/Rescue pull request #30
Opened 2020-12-29 09:22 UTC by patel-atul

changed footer
![footer rescue](https://user-images.githubusercontent.com/73336171/103273419-48a45600-49e5-11eb-9481-ac8e1e5543d9.png)
![footer rescue 1](https://user-images.githubusercontent.com/73336171/103273425-4c37dd00-49e5-11eb-8eea-555a79d990c9.png)
![footer rescue 2](https://user-images.githubusercontent.com/73336171/103273434-5063fa80-49e5-11eb-9cc5-1fad2192e2a1.png)

2020-12-31 15:16 UTC, swapnilsparsh commented
@patel-atul Footer which you have made is awesome.
You have to make just few changes,

1. Use the same font which is used in the website
2. Footer which you have made is only showing on home page, it should show on every page.

2020-12-31 15:16 UTC, swapnilsparsh requested changes
@patel-atul Footer which you have made is awesome.
You have to make just few changes,

1. Use the same font which is used in the website
2. Footer which you have made is only showing on home page, it should show on every page.

2021-01-01 05:35 UTC, patel-atul commented
@swapnilsparsh Made changes you have requested please have a look at it.

2021-01-01 16:41 UTC, swapnilsparsh requested changes
Some last few changes
1. Change the colour of footer to the colour of header.
2. Dont use any social media reference in footer just keep it simple as it was earlier and remove the newsletter.
3. Add a Developer option in footer on clicking on it developer section should open.

2021-01-02 07:05 UTC, patel-atul commented
Made all the changes requested.

2021-01-02 18:05 UTC, swapnilsparsh requested changes
![Annotation 2021-01-02 233222](https://user-images.githubusercontent.com/69387608/103463530-141cfb00-4d53-11eb-9665-881fd5c8346a.png)
![Annotation 2021-01-02 233237](https://user-images.githubusercontent.com/69387608/103463532-167f5500-4d53-11eb-9942-460a8ae0b2d5.png)
![Annotation 2021-01-02 233257](https://user-images.githubusercontent.com/69387608/103463536-17b08200-4d53-11eb-81cd-66fff9339434.png)

It's showing error when clicking on the link in the footer.

2021-01-05 03:51 UTC, patel-atul commented
@swapnilsparsh  I have not changed anything in developers page it was already like that i have only linked the page in footer and also I dont know how to fix this.

2021-01-05 04:00 UTC, swapnilsparsh commented
> @swapnilsparsh  I have not changed anything in developers page it was already like that i have only linked the page in footer and also I dont know how to fix this.

If you dont fix this then I can't merge your PR.

2021-01-06 04:44 UTC, patel-atul commented
@swapnilsparsh I have no know knowledge of python or django. I can only do frontend. I have tried some solutions from stack overflow but didn't work please help me.

2021-01-06 17:02 UTC, swapnilsparsh commented
> @swapnilsparsh I have no know knowledge of python or django. I can only do frontend. I have tried some solutions from stack overflow but didn't work please help me.

You have to link the file then your problem will resolve

2021-01-06 17:38 UTC, musavveer commented
Shall I give it a try @swapnilsparsh

2021-01-17 12:37 UTC, closed without merging