made the top bar's orientation proper after logging in
swapnilsparsh/Rescue pull request #66
Opened 2021-01-18 18:35 UTC by Sloth-Panda

corresponds to issue-> #57

2021-01-18 19:07 UTC, sanjay270899 requested changes

2021-01-18 19:07 UTC, sanjay270899 commented on main_app/mail.py
> +    server.login("achyut662cs@gmail.com", "662cs@12345")
Remove your Email ID and Password, and change it "Email ID" and "Password" respectively.

2021-01-18 19:07 UTC, sanjay270899 commented on main_app/mail.py
> +    msg['From'] = formataddr(("TEAM RESCUE", "achyut662cs@gmail.com"))
Here also. @Sloth-Panda

2021-01-18 19:07 UTC, sanjay270899 commented on main_app/mail.py
>      server.quit()
Here also.

2021-01-18 19:12 UTC, Sloth-Panda commented
oh ,  forgot to remove that

2021-01-18 19:13 UTC, sanjay270899 commented
@Sloth-Panda I will suggest changing the password of your Gmail account right now.

2021-01-18 19:17 UTC, Sloth-Panda commented
@sanjay270899 have corrected that

2021-01-18 19:20 UTC, sanjay270899 commented
@Sloth-Panda Now it is fine. Also, I will suggest you to change the password of your google account.

2021-01-18 19:21 UTC, Sloth-Panda commented
@sanjay270899 changing still delete the photos

2021-01-19 10:07 UTC, swapnilsparsh commented
Issue has been resolved #67

2021-01-19 10:07 UTC, closed without merging